### ISSUE TITLE
H.264 failing on Firefox in “Block Audio” mode?

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1287] opened 2023-01-27 18:57 UTC
While testing audio-related things on a `2.5.2-22-g654a464` Pro build on Bullseye, I noticed that H.264 fails altogether if autoplay permissions are set to “Block Audio” (which I believe is the global default):

<img width="836" alt="Screenshot 2023-01-27 at 19 53 04" src="https://user-images.githubusercontent.com/83721279/215170900-ea181c0e-707f-467f-81f6-a2ae48812c89.png">

I don’t know why this is, because in the DOM, the video element is correctly set to muted:

<img width="546" alt="Screenshot 2023-01-27 at 19 55 43" src="https://user-images.githubusercontent.com/83721279/215171383-bfe9c413-6971-41fd-a254-dd5706949fe3.png">

Then, when `console.log`’ing the `muted` property in the code, however, it’s set to `false`:

<img width="141" alt="Screenshot 2023-01-27 at 19 56 15" src="https://user-images.githubusercontent.com/83721279/215171472-7b3788fd-7d95-44c4-981e-448fd25384f5.png">

Could someone confirm this independently? I seem to be able to reproduce this, even after restarting the browser, but based on all the weird behaviour that I’ve seen around audio, I’m not 100% sure actually…

**Comment by mtlynch** [comment] 2023-01-27 19:10
Yeah, I'm seeing the same:

![image](https://user-images.githubusercontent.com/7783288/215174413-ae5ffc1e-35c0-4b57-8d8b-252af2ab9b23.png)

I flashed `2.5.2-22-g654a464` and then did nothing except switch video mode to H.264, and it failed.

**Comment by jdeanwallace** [comment] 2023-02-03 13:10
Yes I can confirm that this issue would be fixed by https://github.com/tiny-pilot/tinypilot/pull/1288.

With regards to the root cause, I'm struggling to find a definitive explanation.

What I'm experiencing though is that Firefox is not respecting the `video` element's `muted` attribute.

However, explicitly setting `muted = true` in JS before attempting to play the video fixes this particular issue and results in H.264 video to autoplay successfully.

**Closed as completed** 2023-02-06 15:22 UTC
Labels: bug
