### ISSUE TITLE
Underscores cannot be entered.

### ISSUE THREAD

**Issue by mitubato** [tiny-pilot/tinypilot#1319] opened 2023-02-22 01:53 UTC
Hello.

I'm using Version: 1.8.1-22 [7329336] and I can't type the underscore.
The keyboard I'm using is 109A.
Version: 1.8.1-22 [7329336]

If you try to enter it, the following will be displayed and it will not actually be entered.
![image](https://user-images.githubusercontent.com/62734742/220499773-74b18f54-2c9d-4fe3-b3ea-12c06a99d17d.png)

**Comment by mtlynch** [comment] 2023-02-28 10:57
Thanks for reporting this!

@db39 - Can you assist here?

**Comment by db39** [comment] 2023-02-28 12:00
Hi @mitubato, sorry that you're running into this keyboard input issue.

Just to confirm, is the keyboard layout you're using a Japanese layout - like this one?

![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/KB_Japanese.svg/840px-KB_Japanese.svg.png)

Are you able to enter `_` using TinyPilot's on-screen keyboard? To do this, go to View > Show Keyboard (if it isn't already open), then click `shift` + `_` using your mouse. If that works, you can use the on-screen keyboard as a workaround while we try and figure out the root cause of the issue.

Finally, can you go to [keycode.info](https://www.toptal.com/developers/keycode) and type an underscore? Could you share a screenshot of the output like my example?:

![image](https://user-images.githubusercontent.com/88856877/221848047-63fc1f1a-718c-4f36-ab69-da626e64bae6.png)

**Comment by mitubato** [comment] 2023-03-01 04:28
こんにちは@db39

使用しているキー配列は画像のものと同じです。
TinyPilotのスクリーンキーボードでは’_’を入力すると’=’と表示されます。

keycode.infoでは226と出ました。
![image](https://user-images.githubusercontent.com/62734742/222044880-8b8ba3e1-6807-41b8-b1fa-85f34102c5d8.png)

**Comment by db39** [comment] 2023-03-02 12:36
Thanks for sharing that information, @mitubato!

Unfortunately, TinyPilot doesn't have support for the `IntlRo` key. And I'm not sure if we'd be able to add support for that key in future due to how TinyPilot currently handles keyboard input.

One option is to paste the character (using Actions > Paste in the TinyPilot web interface menu). But I understand that this is an inconvenient workaround.

I'm sorry that I haven't been able to find a better solution for this. Please let me know if you have any other questions.

**Comment by mtlynch** [comment] 2023-03-02 16:12
I think we should be able to fix this.

@db39 - Can you try configuring an on-screen keyboard on a test machine with the Japanese layout that @mitubato is using and then [use evtest](https://github.com/tiny-pilot/tinypilot/issues/361#issuecomment-1419699354) to print the raw HID codes, then press Shift + IntlRo on the on-screen keyboard?

![image](https://user-images.githubusercontent.com/7783288/222484381-7c10daf4-ba30-4039-8a1f-f1bb761d394f.png)

If we can capture what HID code that key generates on a Japanese system, then we can add a mapping for IntlRo in [js_to_hid.py](https://github.com/tiny-pilot/tinypilot/blob/master/app/js_to_hid.py).

You can test by sending raw HID codes to the TinyPilot emulated keyboard by echoing to `/dev/hidg0`. For example, this simulates a keypress of the `i` key (HID code = `0x0c`):

```bash
echo -ne "\0\0\xc\0\0\0\0\0" > /dev/hidg0
```

**Comment by mitubato** [comment] 2023-03-03 09:31
@db39 Thank you for checking.

@mtlynch
hello.
I tried to check, but I couldn't find/dev/input/event*.
Do I need to make any settings?

`root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
root@raspberrypi:~#
root@raspberrypi:~# cat /etc/rpi-issue
Raspberry Pi reference 2021-05-07
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, dcfd74d7d1fa293065ac6d565711e9ff891fe2b8, stage2
root@raspberrypi:~#`

`root@raspberrypi:~# vcgencmd get_config int
arm_freq=1500
audio_pwm_mode=514
camera_auto_detect=-1
config_hdmi_boost=5
core_freq=500
core_freq_min=200
disable_commandline_tags=2
disable_l2cache=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
dvfs=3
enable_gic=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=500
gpu_freq_min=250
init_uart_clock=0x2dc6c00
lcd_framerate=60
mask_gpu_interrupt0=1024
mask_gpu_interrupt1=0x10000
max_framebuffers=2
over_voltage_avs=-17500
pause_burst_frames=1
program_serial_random=1
total_mem=4096
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_pixel_freq_limit:0=0x11e1a300
hdmi_pixel_freq_limit:1=0x11e1a300`

**Comment by mtlynch** [comment] 2023-03-03 09:44
@mitubato - evtest would run on the test machine, not on the TinyPilot device. We're trying to determine what HID code the target machine sees when the user presses the `IntlRo` button on a Japanese system.

**Comment by mitubato** [comment] 2023-03-03 11:22
@mtlynch 
excuse me.

I got the following result:

echo -ne "\0\0\x89\0\0\0\0\0" > /dev/hidg0
  -> \

Since I didn't know the description to send at the same time as 'Shift', it is '/', but if it can be sent at the same time, it seems that '_' can be entered.

`Testing ... (interrupt to exit)
Event: time 1677841534.837291, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2a
Event: time 1677841534.837291, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 1
Event: time 1677841534.837291, -------------- SYN_REPORT ------------
Event: time 1677841535.092803, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2a
Event: time 1677841535.092803, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 2
Event: time 1677841535.092803, -------------- SYN_REPORT ------------
Event: time 1677841535.113115, type 4 (EV_MSC), code 4 (MSC_SCAN), value 73
Event: time 1677841535.113115, type 1 (EV_KEY), code 89 (KEY_RO), value 1
Event: time 1677841535.113115, -------------- SYN_REPORT ------------
Event: time 1677841535.283676, type 4 (EV_MSC), code 4 (MSC_SCAN), value 73
Event: time 1677841535.283676, type 1 (EV_KEY), code 89 (KEY_RO), value 0
Event: time 1677841535.283676, -------------- SYN_REPORT ------------
Event: time 1677841535.495541, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2a
Event: time 1677841535.495541, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 0
Event: time 1677841535.495541, -------------- SYN_REPORT ------------

Event: time 1677841544.337540, type 4 (EV_MSC), code 4 (MSC_SCAN), value 17
Event: time 1677841544.337540, type 1 (EV_KEY), code 23 (KEY_I), value 1
Event: time 1677841544.337540, -------------- SYN_REPORT ------------
Event: time 1677841544.446323, type 4 (EV_MSC), code 4 (MSC_SCAN), value 17
Event: time 1677841544.446323, type 1 (EV_KEY), code 23 (KEY_I), value 0
Event: time 1677841544.446323, -------------- SYN_REPORT ------------
^Croot@Ubuntu:~#`

**Comment by db39** [comment] 2023-03-06 19:47
Thanks for sharing that result @mitubato. I tried to use `echo -ne "\0\0\x89\0\0\0\0\0" > /dev/hidg0` to test this on my device, but it doesn't seem work as expected.

Can you share  `evtest`'s output when you type `_` on your Japanese keyboard again?

**Comment by mitubato** [comment] 2023-03-08 01:33
Yes! Share again.
I think the reason why it didn't go well is that the keyboard layout set on the PC connected to TinyPilot is not for Japanese.

`root@ubuntu:~# ./evtest/evtest /dev/input/event3
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x1 product 0x1 version 0xab41
Input device name: "AT Translated Set 2 keyboard"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 112 (KEY_MACRO)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 118 (KEY_KPPLUSMINUS)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 143 (KEY_WAKEUP)
    Event code 155 (KEY_MAIL)
    Event code 156 (KEY_BOOKMARKS)
    Event code 157 (KEY_COMPUTER)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 172 (KEY_HOMEPAGE)
    Event code 173 (KEY_REFRESH)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 217 (KEY_SEARCH)
    Event code 226 (KEY_MEDIA)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 17 (EV_LED)
    Event code 0 (LED_NUML) state 0
    Event code 1 (LED_CAPSL) state 0
    Event code 2 (LED_SCROLLL) state 0
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
Properties:
Testing ... (interrupt to exit)
Event: time 1678238373.501312, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2a
Event: time 1678238373.501312, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 1
Event: time 1678238373.501312, -------------- SYN_REPORT ------------
Event: time 1678238373.634227, type 4 (EV_MSC), code 4 (MSC_SCAN), value 73
Event: time 1678238373.634227, type 1 (EV_KEY), code 89 (KEY_RO), value 1
Event: time 1678238373.634227, -------------- SYN_REPORT ------------
Event: time 1678238373.756448, type 4 (EV_MSC), code 4 (MSC_SCAN), value 73
Event: time 1678238373.756448, type 1 (EV_KEY), code 89 (KEY_RO), value 0
Event: time 1678238373.756448, -------------- SYN_REPORT ------------
Event: time 1678238373.834622, type 4 (EV_MSC), code 4 (MSC_SCAN), value 2a
Event: time 1678238373.834622, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 0
Event: time 1678238373.834622, -------------- SYN_REPORT ------------
^C
root@ubuntu:~#`
![Screenshot from 2023-03-08 01-12-45](https://user-images.githubusercontent.com/62734742/223596060-1fc23eb8-ba04-42ca-9f6b-ecb88e39d628.png)
![image](https://user-images.githubusercontent.com/62734742/223596098-7a7d837a-5d46-4fff-a26e-3e4b3ab357df.png)

**Comment by db39** [comment] 2023-03-09 12:23
Thanks for that information, @mitubato.

There are a couple more tests I'd like to try. 

For these tests, can you make sure your target computer is using a Japanese language layout?

Could you SSH into your TinyPilot and then run the following command:

```bash
echo -ne "\x02\0\x87\0\0\0\0\0" > /dev/hidg0
```

I'm expecting that command to output `＿`. Can you share a screenshot of the output (in a text editor or on keycode.info)?

Then try this command:

```bash
echo -ne "\0\0\x89\0\0\0\0\0" > /dev/hidg0
```

This time, I'm expecting it to output `￥`. Can you share a screenshot of the output of this too?

If they both output the expected characters, I can add them to TinyPilot's supported keycodes.

**Comment by mitubato** [comment] 2023-03-13 09:02
Hi! @db39 
I am late.
We will report the results!
You have successfully entered an underscore!

’echo -ne "\x02\0\x87\0\0\0\0\0" > /dev/hidg0’
![image](https://user-images.githubusercontent.com/62734742/224653823-f5e003be-4569-4f7a-ad93-48ba63117fb1.png)

’echo -ne "\0\0\x89\0\0\0\0\0" > /dev/hidg0’
![image](https://user-images.githubusercontent.com/62734742/224654376-d2228f86-d228-4f26-8179-52a5893b7581.png)

**Comment by db39** [comment] 2023-03-13 12:54
Fantastic! Thanks so much for helping with that, @mitubato.

I'll create a branch to add those codes to TinyPilot. Once they're merged into the main branch, you should be able to use those keys on your keyboard. I will let you know once we've done that.

**Closed** 2023-03-13 13:44 UTC
Labels: question

**Comment by mitubato** [comment] 2023-03-14 04:08
@db39 
thank you very much!
We have confirmed that you can enter underscores in TinyPilot!

**Comment by db39** [comment] 2023-03-14 12:40
No problem, @mitubato, I'm glad we were able to find a solution.

I merged the changes into the repository. So once we release the new version of TinyPilot you should have support for `＿` and `￥` keys on  your hardware keyboard.

If you want to incorporate the changes now, you can edit your files to match [my commit](https://github.com/tiny-pilot/tinypilot/pull/1323/commits/af217affd1f63678deec2d8ee54b55d64089088d).
